import dynamic from "next/dynamic";
import { type Processes } from "contexts/process/types";
import { FOLDER_ICON, TASKBAR_HEIGHT } from "utils/constants";

const directory: Processes = {
  BoxedWine: {
    Component: dynamic(() => import("components/apps/BoxedWine")),
    allowResizing: false,
    backgroundColor: "#000",
    defaultSize: {
      height: 480,
      width: 640,
    },
    dependantLibs: ["/Program Files/BoxedWine/boxedwine.wasm"],
    icon: "/System/Icons/boxedwine.webp",
    libs: [
      "/Program Files/BoxedWine/browserfs.boxedwine.js",
      "/Program Files/BoxedWine/boxedwine-shell.js",
      "/Program Files/BoxedWine/boxedwine.js",
    ],
    lockAspectRatio: true,
    singleton: true,
    title: "BoxedWine",
  },
  Browser: {
    Component: dynamic(() => import("components/apps/Browser")),
    backgroundColor: "#FFF",
    defaultSize: {
      height: 500,
      width: 600,
    },
    icon: "/System/Icons/chromium.webp",
    title: "Browser",
  },
  ClassiCube: {
    Component: dynamic(() => import("components/apps/ClassiCube")),
    backgroundColor: "#201E20",
    defaultSize: {
      height: 420,
      width: 640,
    },
    hideMaximizeButton: true,
    icon: "/System/Icons/classicube.webp",
    libs: ["/Program Files/ClassiCube/ClassiCube.js"],
    title: "ClassiCube",
  },
  DXBall: {
    Component: dynamic(() => import("components/apps/DX-Ball")),
    backgroundColor: "#000",
    icon: "/System/Icons/dxball.webp",
    libs: ["/Program Files/DX-Ball/game.js"],
    lockAspectRatio: true,
    singleton: true,
    title: "DX-Ball",
  },
  Emulator: {
    Component: dynamic(() => import("components/apps/Emulator")),
    backgroundColor: "#000",
    defaultSize: {
      height: 400,
      width: 600,
    },
    dependantLibs: [
      "/Program Files/EmulatorJs/emu-css.min.css",
      "/Program Files/EmulatorJs/emulator.min.js",
    ],
    icon: "/System/Icons/emulator.webp",
    libs: ["/Program Files/EmulatorJs/loader.js"],
    lockAspectRatio: true,
    singleton: true,
    title: "Emulator",
  },
  FileExplorer: {
    Component: dynamic(() => import("components/apps/FileExplorer")),
    backgroundColor: "#202020",
    defaultSize: {
      height: 325,
      width: 447,
    },
    icon: FOLDER_ICON,
    title: "File Explorer",
  },
  JSDOS: {
    Component: dynamic(() => import("components/apps/JSDOS")),
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 200,
      width: 320,
    },
    dependantLibs: ["/Program Files/js-dos/wdosbox.wasm"],
    icon: "/System/Icons/jsdos.webp",
    libs: [
      "/Program Files/js-dos/emulators.js",
      "/Program Files/js-dos/emulators-ui.js",
    ],
    lockAspectRatio: true,
    title: "js-dos v7",
  },
  OpenType: {
    Component: dynamic(() => import("components/apps/OpenType")),
    backgroundColor: "#FFF",
    icon: "/System/Icons/opentype.webp",
    preferProcessIcon: true,
    title: "OpenType",
  },
  OpenWith: {
    Component: dynamic(() => import("components/system/Dialogs/OpenWith")),
    allowResizing: false,
    backgroundColor: "#FFF",
    defaultSize: {
      height: 492,
      width: 392,
    },
    dialogProcess: true,
    hideTaskbarEntry: true,
    hideTitlebar: true,
    icon: "/System/Icons/unknown.webp",
    title: "Open With",
  },
  Paint: {
    Component: dynamic(() => import("components/apps/Paint")),
    backgroundColor: "#808080",
    icon: "/System/Icons/paint.webp",
    libs: ["/Program Files/jspaint/index.html"],
    title: "Paint",
  },
  Photos: {
    Component: dynamic(() => import("components/apps/Photos")),
    backgroundColor: "#222",
    defaultSize: {
      height: 432,
      width: 576,
    },
    hideTitlebarIcon: true,
    icon: "/System/Icons/photos.webp",
    title: "Photos",
  },
  Properties: {
    Component: dynamic(() => import("components/system/Dialogs/Properties")),
    allowResizing: false,
    backgroundColor: "rgb(240, 240, 240)",
    defaultSize: {
      height: 412,
      width: 361,
    },
    dialogProcess: true,
    hideMaximizeButton: true,
    hideMinimizeButton: true,
    icon: "",
    title: "Properties",
  },
  Quake3: {
    Component: dynamic(() => import("components/apps/Quake3")),
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 480,
      width: 640,
    },
    icon: "/System/Icons/quake3.webp",
    libs: ["/Program Files/Quake3/Quake3Game.js"],
    title: "Quake III Arena",
  },
  Run: {
    Component: dynamic(() => import("components/system/Dialogs/Run")),
    allowResizing: false,
    defaultSize: {
      height: 174,
      width: 397,
    },
    dialogProcess: true,
    hideMaximizeButton: true,
    hideMinimizeButton: true,
    icon: "/System/Icons/run.webp",
    initialRelativePosition: {
      bottom: TASKBAR_HEIGHT + 11,
      left: 15,
    },
    singleton: true,
    title: "Run",
  },
  SpaceCadet: {
    Component: dynamic(() => import("components/apps/SpaceCadet")),
    backgroundColor: "#000",
    defaultSize: {
      height: 428,
      width: 600,
    },
    dependantLibs: ["/Program Files/SpaceCadet/SpaceCadetPinball.wasm"],
    icon: "/System/Icons/pinball.webp",
    libs: ["/Program Files/SpaceCadet/SpaceCadetPinball.js"],
    lockAspectRatio: true,
    singleton: true,
    title: "Space Cadet",
  },
  Terminal: {
    Component: dynamic(() => import("components/apps/Terminal")),
    backgroundColor: "rgba(12, 12, 12, 0.5)",
    defaultSize: {
      height: 374,
      width: 615,
    },
    icon: "/System/Icons/xterm.webp",
    libs: [
      "/Program Files/Xterm.js/xterm.css",
      "/Program Files/Xterm.js/xterm.js",
      "/Program Files/Xterm.js/xterm-addon-fit.js",
      "/Program Files/Xterm.js/local-echo.js",
    ],
    preferProcessIcon: true,
    title: "Terminal",
  },
  Transfer: {
    Component: dynamic(() => import("components/system/Dialogs/Transfer")),
    allowResizing: false,
    backgroundColor: "#FFF",
    defaultSize: {
      height: 163,
      width: 400,
    },
    dialogProcess: true,
    icon: "/System/Icons/copying.webp",
    title: "",
  },
  V86: {
    Component: dynamic(() => import("components/apps/V86")),
    allowResizing: false,
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 200,
      width: 320,
    },
    dependantLibs: ["/Program Files/Virtual x86/v86.wasm"],
    icon: "/System/Icons/v86.webp",
    libs: ["/Program Files/Virtual x86/libv86.js"],
    preferProcessIcon: true,
    title: "Virtual x86",
  },
  VideoPlayer: {
    Component: dynamic(() => import("components/apps/VideoPlayer")),
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 390,
      width: 640,
    },
    icon: "/System/Icons/vlc.webp",
    libs: [
      "/Program Files/Video.js/video-js.min.css",
      "/Program Files/Video.js/video.min.js",
      "/Program Files/Video.js/Youtube.min.js",
    ],
    title: "Video Player",
  },
  Vim: {
    Component: dynamic(() => import("components/apps/Vim")),
    allowResizing: false,
    backgroundColor: "#222324",
    defaultSize: {
      height: 448,
      width: 595,
    },
    icon: "/System/Icons/vim.webp",
    libs: ["/Program Files/Vim.js/vim.js"],
    singleton: true,
    title: "Vim",
  },
  Webamp: {
    Component: dynamic(() => import("components/apps/Webamp")),
    allowResizing: false,
    hasWindow: false,
    icon: "/System/Icons/webamp.webp",
    libs: ["/Program Files/Webamp/webamp.bundle.min.js"],
    singleton: true,
    title: "Webamp",
  },
};

export default directory;
